services:
  worker:
    build: .
    environment:
      APP_ID: $APP_ID  
      API_HASH: $API_HASH  
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      OWNER_ID: $OWNER_ID
      CHANNEL_ID: $CHANNEL_ID
      FORCE_SUB_CHANNEL: $FORCE_SUB_CHANNEL             
      START_MESSAGE: $START_MESSAGE
      CUSTOM_CAPTION: $CUSTOM_CAPTION
      FORCE_SUB_MESSAGE: $FORCE_SUB_MESSAGE
      ADMINS: $ADMINS
      DB_URI: $DB_URI
      PROTECT_CONTENT: $PROTECT_CONTENT
    resources:
      cpu: 1000m
      memory: 3Gi
